# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainView.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1355, 1231)
        self.CentralView = QtWidgets.QWidget(MainWindow)
        self.CentralView.setObjectName("CentralView")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.CentralView)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.main_window_layout = QtWidgets.QHBoxLayout()
        self.main_window_layout.setObjectName("main_window_layout")
        self.left_panel = QtWidgets.QGroupBox(self.CentralView)
        self.left_panel.setMinimumSize(QtCore.QSize(370, 500))
        self.left_panel.setMaximumSize(QtCore.QSize(300, 16777215))
        self.left_panel.setObjectName("left_panel")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.left_panel)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.left_scroll = QtWidgets.QScrollArea(self.left_panel)
        self.left_scroll.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.left_scroll.setWidgetResizable(True)
        self.left_scroll.setObjectName("left_scroll")
        self.left_scroll_results = QtWidgets.QWidget()
        self.left_scroll_results.setGeometry(QtCore.QRect(0, 0, 354, 1175))
        self.left_scroll_results.setObjectName("left_scroll_results")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.left_scroll_results)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.left_scroll_results_vbox_layout = QtWidgets.QVBoxLayout()
        self.left_scroll_results_vbox_layout.setObjectName("left_scroll_results_vbox_layout")
        self.verticalLayout_10.addLayout(self.left_scroll_results_vbox_layout)
        self.left_scroll.setWidget(self.left_scroll_results)
        self.verticalLayout_6.addWidget(self.left_scroll)
        self.main_window_layout.addWidget(self.left_panel)
        self.mid_panel = QtWidgets.QGroupBox(self.CentralView)
        self.mid_panel.setMinimumSize(QtCore.QSize(300, 500))
        self.mid_panel.setObjectName("mid_panel")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.mid_panel)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.main_image_scroll = QtWidgets.QScrollArea(self.mid_panel)
        self.main_image_scroll.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.main_image_scroll.setWidgetResizable(True)
        self.main_image_scroll.setObjectName("main_image_scroll")
        self.main_scoll_vbox_layout = QtWidgets.QWidget()
        self.main_scoll_vbox_layout.setGeometry(QtCore.QRect(0, 0, 573, 1175))
        self.main_scoll_vbox_layout.setObjectName("main_scoll_vbox_layout")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.main_scoll_vbox_layout)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.main_image_label = QtWidgets.QLabel(self.main_scoll_vbox_layout)
        self.main_image_label.setText("")
        self.main_image_label.setObjectName("main_image_label")
        self.verticalLayout_8.addWidget(self.main_image_label)
        self.main_image_scroll.setWidget(self.main_scoll_vbox_layout)
        self.verticalLayout_7.addWidget(self.main_image_scroll)
        self.main_window_layout.addWidget(self.mid_panel)
        self.right_panel = QtWidgets.QGroupBox(self.CentralView)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.right_panel.sizePolicy().hasHeightForWidth())
        self.right_panel.setSizePolicy(sizePolicy)
        self.right_panel.setMinimumSize(QtCore.QSize(370, 500))
        self.right_panel.setMaximumSize(QtCore.QSize(300, 16777215))
        self.right_panel.setTitle("Details")
        self.right_panel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.right_panel.setFlat(False)
        self.right_panel.setObjectName("right_panel")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.right_panel)
        self.verticalLayout_9.setContentsMargins(-1, 2, 2, 2)
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.groupBox_3 = QtWidgets.QGroupBox(self.right_panel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setMinimumSize(QtCore.QSize(350, 60))
        self.groupBox_3.setMaximumSize(QtCore.QSize(350, 60))
        self.groupBox_3.setBaseSize(QtCore.QSize(350, 50))
        self.groupBox_3.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_3.setFlat(False)
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.custom_label = QtWidgets.QLabel(self.groupBox_3)
        self.custom_label.setMinimumSize(QtCore.QSize(0, 0))
        self.custom_label.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.custom_label.setFont(font)
        self.custom_label.setStyleSheet("margin-left : 23px")
        self.custom_label.setObjectName("custom_label")
        self.horizontalLayout.addWidget(self.custom_label)
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
        self.lineEdit.setSizePolicy(sizePolicy)
        self.lineEdit.setMinimumSize(QtCore.QSize(150, 30))
        self.lineEdit.setMaximumSize(QtCore.QSize(150, 16777215))
        self.lineEdit.setStyleSheet("margin-left : 5px")
        self.lineEdit.setDragEnabled(False)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.input_btn = QtWidgets.QPushButton(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.input_btn.sizePolicy().hasHeightForWidth())
        self.input_btn.setSizePolicy(sizePolicy)
        self.input_btn.setMinimumSize(QtCore.QSize(31, 31))
        self.input_btn.setMaximumSize(QtCore.QSize(31, 31))
        self.input_btn.setText("")
        self.input_btn.setObjectName("input_btn")
        self.horizontalLayout.addWidget(self.input_btn)
        self.verticalLayout_9.addWidget(self.groupBox_3, 0, QtCore.Qt.AlignHCenter)
        self.groupBox_2 = QtWidgets.QGroupBox(self.right_panel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setMinimumSize(QtCore.QSize(350, 60))
        self.groupBox_2.setMaximumSize(QtCore.QSize(350, 60))
        self.groupBox_2.setBaseSize(QtCore.QSize(350, 50))
        self.groupBox_2.setTitle("")
        self.groupBox_2.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("margin-left : 23px")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3, 0, QtCore.Qt.AlignLeft)
        self.custom_line_edit = QtWidgets.QLineEdit(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.custom_line_edit.sizePolicy().hasHeightForWidth())
        self.custom_line_edit.setSizePolicy(sizePolicy)
        self.custom_line_edit.setMinimumSize(QtCore.QSize(150, 30))
        self.custom_line_edit.setMaximumSize(QtCore.QSize(150, 16777215))
        self.custom_line_edit.setStyleSheet("margin-left : 5px")
        self.custom_line_edit.setObjectName("custom_line_edit")
        self.horizontalLayout_2.addWidget(self.custom_line_edit)
        self.output_btn = QtWidgets.QPushButton(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.output_btn.sizePolicy().hasHeightForWidth())
        self.output_btn.setSizePolicy(sizePolicy)
        self.output_btn.setMinimumSize(QtCore.QSize(31, 31))
        self.output_btn.setMaximumSize(QtCore.QSize(31, 31))
        self.output_btn.setText("")
        self.output_btn.setObjectName("output_btn")
        self.horizontalLayout_2.addWidget(self.output_btn)
        self.verticalLayout_9.addWidget(self.groupBox_2, 0, QtCore.Qt.AlignHCenter)
        self.groupBox = QtWidgets.QGroupBox(self.right_panel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(350, 60))
        self.groupBox.setMaximumSize(QtCore.QSize(350, 60))
        self.groupBox.setBaseSize(QtCore.QSize(350, 50))
        self.groupBox.setTitle("")
        self.groupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.fav_label = QtWidgets.QLabel(self.groupBox)
        self.fav_label.setMinimumSize(QtCore.QSize(0, 0))
        self.fav_label.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.fav_label.setFont(font)
        self.fav_label.setStyleSheet("margin-left : 23px")
        self.fav_label.setObjectName("fav_label")
        self.horizontalLayout_3.addWidget(self.fav_label)
        self.fav_pips_combo_box = QtWidgets.QComboBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fav_pips_combo_box.sizePolicy().hasHeightForWidth())
        self.fav_pips_combo_box.setSizePolicy(sizePolicy)
        self.fav_pips_combo_box.setMinimumSize(QtCore.QSize(0, 0))
        self.fav_pips_combo_box.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.fav_pips_combo_box.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.fav_pips_combo_box.setStyleSheet("margin-left : 5px")
        self.fav_pips_combo_box.setObjectName("fav_pips_combo_box")
        self.horizontalLayout_3.addWidget(self.fav_pips_combo_box)
        self.save_btn = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.save_btn.sizePolicy().hasHeightForWidth())
        self.save_btn.setSizePolicy(sizePolicy)
        self.save_btn.setMinimumSize(QtCore.QSize(31, 31))
        self.save_btn.setMaximumSize(QtCore.QSize(31, 31))
        self.save_btn.setText("")
        self.save_btn.setObjectName("save_btn")
        self.horizontalLayout_3.addWidget(self.save_btn)
        self.verticalLayout_9.addWidget(self.groupBox, 0, QtCore.Qt.AlignHCenter)
        self.groupBox_4 = QtWidgets.QGroupBox(self.right_panel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_4.sizePolicy().hasHeightForWidth())
        self.groupBox_4.setSizePolicy(sizePolicy)
        self.groupBox_4.setMinimumSize(QtCore.QSize(350, 60))
        self.groupBox_4.setMaximumSize(QtCore.QSize(350, 60))
        self.groupBox_4.setBaseSize(QtCore.QSize(50, 350))
        self.groupBox_4.setAutoFillBackground(False)
        self.groupBox_4.setTitle("")
        self.groupBox_4.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_4.setFlat(False)
        self.groupBox_4.setObjectName("groupBox_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.groupBox_4)
        self.horizontalLayout_4.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.run_btn = QtWidgets.QPushButton(self.groupBox_4)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.run_btn.setFont(font)
        self.run_btn.setObjectName("run_btn")
        self.horizontalLayout_4.addWidget(self.run_btn)
        self.verticalLayout_9.addWidget(self.groupBox_4, 0, QtCore.Qt.AlignHCenter)
        self.pip_collapsable = QtWidgets.QGroupBox(self.right_panel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pip_collapsable.sizePolicy().hasHeightForWidth())
        self.pip_collapsable.setSizePolicy(sizePolicy)
        self.pip_collapsable.setMinimumSize(QtCore.QSize(350, 350))
        self.pip_collapsable.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.pip_collapsable.setBaseSize(QtCore.QSize(350, 350))
        self.pip_collapsable.setTitle("Pipeline")
        self.pip_collapsable.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.pip_collapsable.setFlat(True)
        self.pip_collapsable.setObjectName("pip_collapsable")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.pip_collapsable)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pip_collapse_button = QtWidgets.QHBoxLayout()
        self.pip_collapse_button.setObjectName("pip_collapse_button")
        self.current_pip_label = QtWidgets.QLabel(self.pip_collapsable)
        self.current_pip_label.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.current_pip_label.setFont(font)
        self.current_pip_label.setStyleSheet("margin-left : 20px")
        self.current_pip_label.setText("")
        self.current_pip_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.current_pip_label.setObjectName("current_pip_label")
        self.pip_collapse_button.addWidget(self.current_pip_label)
        self.add_btn = QtWidgets.QPushButton(self.pip_collapsable)
        self.add_btn.setMinimumSize(QtCore.QSize(31, 31))
        self.add_btn.setMaximumSize(QtCore.QSize(31, 31))
        self.add_btn.setText("")
        self.add_btn.setObjectName("add_btn")
        self.pip_collapse_button.addWidget(self.add_btn)
        self.delete_btn = QtWidgets.QPushButton(self.pip_collapsable)
        self.delete_btn.setMinimumSize(QtCore.QSize(31, 31))
        self.delete_btn.setMaximumSize(QtCore.QSize(31, 31))
        self.delete_btn.setText("")
        self.delete_btn.setObjectName("delete_btn")
        self.pip_collapse_button.addWidget(self.delete_btn)
        self.verticalLayout_2.addLayout(self.pip_collapse_button)
        self.pip_scroll = QtWidgets.QScrollArea(self.pip_collapsable)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pip_scroll.sizePolicy().hasHeightForWidth())
        self.pip_scroll.setSizePolicy(sizePolicy)
        self.pip_scroll.setMinimumSize(QtCore.QSize(0, 200))
        self.pip_scroll.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.pip_scroll.setFrameShadow(QtWidgets.QFrame.Plain)
        self.pip_scroll.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.pip_scroll.setWidgetResizable(True)
        self.pip_scroll.setObjectName("pip_scroll")
        self.pip_scroll_vbox_layout = QtWidgets.QWidget()
        self.pip_scroll_vbox_layout.setGeometry(QtCore.QRect(0, 0, 342, 269))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pip_scroll_vbox_layout.sizePolicy().hasHeightForWidth())
        self.pip_scroll_vbox_layout.setSizePolicy(sizePolicy)
        self.pip_scroll_vbox_layout.setObjectName("pip_scroll_vbox_layout")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.pip_scroll_vbox_layout)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.pip_widget_vbox_layout = QtWidgets.QVBoxLayout()
        self.pip_widget_vbox_layout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.pip_widget_vbox_layout.setSpacing(2)
        self.pip_widget_vbox_layout.setObjectName("pip_widget_vbox_layout")
        self.verticalLayout_4.addLayout(self.pip_widget_vbox_layout)
        self.pip_scroll.setWidget(self.pip_scroll_vbox_layout)
        self.verticalLayout_2.addWidget(self.pip_scroll)
        self.verticalLayout_9.addWidget(self.pip_collapsable)
        self.settings_collapsable = QtWidgets.QGroupBox(self.right_panel)
        self.settings_collapsable.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.settings_collapsable.sizePolicy().hasHeightForWidth())
        self.settings_collapsable.setSizePolicy(sizePolicy)
        self.settings_collapsable.setMinimumSize(QtCore.QSize(350, 500))
        self.settings_collapsable.setAcceptDrops(False)
        self.settings_collapsable.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.settings_collapsable.setFlat(False)
        self.settings_collapsable.setCheckable(False)
        self.settings_collapsable.setObjectName("settings_collapsable")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.settings_collapsable)
        self.verticalLayout.setObjectName("verticalLayout")
        self.select_cat_alg_vbox_layout = QtWidgets.QVBoxLayout()
        self.select_cat_alg_vbox_layout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.select_cat_alg_vbox_layout.setContentsMargins(2, 2, 2, 2)
        self.select_cat_alg_vbox_layout.setSpacing(2)
        self.select_cat_alg_vbox_layout.setObjectName("select_cat_alg_vbox_layout")
        self.verticalLayout.addLayout(self.select_cat_alg_vbox_layout)
        self.setting_scroll = QtWidgets.QScrollArea(self.settings_collapsable)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.setting_scroll.sizePolicy().hasHeightForWidth())
        self.setting_scroll.setSizePolicy(sizePolicy)
        self.setting_scroll.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.setting_scroll.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.setting_scroll.setFrameShadow(QtWidgets.QFrame.Plain)
        self.setting_scroll.setWidgetResizable(True)
        self.setting_scroll.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.setting_scroll.setObjectName("setting_scroll")
        self.settings_scroll_vbox_layout = QtWidgets.QWidget()
        self.settings_scroll_vbox_layout.setGeometry(QtCore.QRect(0, 0, 342, 226))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.settings_scroll_vbox_layout.sizePolicy().hasHeightForWidth())
        self.settings_scroll_vbox_layout.setSizePolicy(sizePolicy)
        self.settings_scroll_vbox_layout.setBaseSize(QtCore.QSize(0, 400))
        self.settings_scroll_vbox_layout.setObjectName("settings_scroll_vbox_layout")
        self.settings_scroll_vbox_layout_2 = QtWidgets.QVBoxLayout(self.settings_scroll_vbox_layout)
        self.settings_scroll_vbox_layout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.settings_scroll_vbox_layout_2.setContentsMargins(-1, 0, -1, -1)
        self.settings_scroll_vbox_layout_2.setObjectName("settings_scroll_vbox_layout_2")
        self.stackedWidget_Settings = QtWidgets.QStackedWidget(self.settings_scroll_vbox_layout)
        self.stackedWidget_Settings.setObjectName("stackedWidget_Settings")
        self.settings_scroll_vbox_layout_2.addWidget(self.stackedWidget_Settings, 0, QtCore.Qt.AlignTop)
        self.setting_scroll.setWidget(self.settings_scroll_vbox_layout)
        self.verticalLayout.addWidget(self.setting_scroll)
        self.verticalLayout_9.addWidget(self.settings_collapsable, 0, QtCore.Qt.AlignTop)
        self.main_window_layout.addWidget(self.right_panel, 0, QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.verticalLayout_3.addLayout(self.main_window_layout)
        MainWindow.setCentralWidget(self.CentralView)
        self.PipelineMenu = QtWidgets.QAction(MainWindow)
        self.PipelineMenu.setObjectName("PipelineMenu")
        self.actionImages = QtWidgets.QAction(MainWindow)
        self.actionImages.setObjectName("actionImages")
        self.actionLoad = QtWidgets.QAction(MainWindow)
        self.actionLoad.setObjectName("actionLoad")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionLoad_2 = QtWidgets.QAction(MainWindow)
        self.actionLoad_2.setObjectName("actionLoad_2")
        self.actionSave_2 = QtWidgets.QAction(MainWindow)
        self.actionSave_2.setObjectName("actionSave_2")
        self.actionLoad_3 = QtWidgets.QAction(MainWindow)
        self.actionLoad_3.setObjectName("actionLoad_3")
        self.actionLoad_Image_Folder = QtWidgets.QAction(MainWindow)
        self.actionLoad_Image_Folder.setObjectName("actionLoad_Image_Folder")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.left_panel.setTitle(_translate("MainWindow", "Immediate Results"))
        self.mid_panel.setTitle(_translate("MainWindow", "Current Selection"))
        self.custom_label.setText(_translate("MainWindow", "Input"))
        self.label_3.setText(_translate("MainWindow", "Output"))
        self.fav_label.setText(_translate("MainWindow", "Pipeline"))
        self.run_btn.setText(_translate("MainWindow", "Run"))
        self.settings_collapsable.setTitle(_translate("MainWindow", "Settings"))
        self.PipelineMenu.setText(_translate("MainWindow", "Pipeline"))
        self.PipelineMenu.setToolTip(_translate("MainWindow", "Menuentrys for saving and loading pipelines"))
        self.actionImages.setText(_translate("MainWindow", "Images"))
        self.actionImages.setToolTip(_translate("MainWindow", "Menu for saving and loading images"))
        self.actionLoad.setText(_translate("MainWindow", "Load"))
        self.actionLoad.setToolTip(_translate("MainWindow", "Load a presaved pipeline in json format"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionSave.setToolTip(_translate("MainWindow", "Save the pipeline settings in a json format. You can load your specified Pipeline in later program calls to process the same settings on other images."))
        self.actionLoad_2.setText(_translate("MainWindow", "Load"))
        self.actionLoad_2.setToolTip(_translate("MainWindow", "Load a presaved Pipeline in json format."))
        self.actionSave_2.setText(_translate("MainWindow", "Specify Output location"))
        self.actionSave_2.setToolTip(_translate("MainWindow", "Specify the default output location in yout file system. Your processed images and graphs will be stored there after processing."))
        self.actionLoad_3.setText(_translate("MainWindow", "Load Image"))
        self.actionLoad_3.setToolTip(_translate("MainWindow", "Load a single image file from the file system."))
        self.actionLoad_Image_Folder.setText(_translate("MainWindow", "Load Image Folder"))
        self.actionLoad_Image_Folder.setToolTip(_translate("MainWindow", "Load a complete folder of images. To display immediate results, the program will use the first image of the folder as default."))

