# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'NefiTemplateView.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1336, 988)
        self.CentralView = QtWidgets.QWidget(MainWindow)
        self.CentralView.setObjectName("CentralView")
        self.gridLayout = QtWidgets.QGridLayout(self.CentralView)
        self.gridLayout.setObjectName("gridLayout")
        self.LeftView = QtWidgets.QWidget(self.CentralView)
        self.LeftView.setMinimumSize(QtCore.QSize(250, 0))
        self.LeftView.setMaximumSize(QtCore.QSize(250, 16777215))
        self.LeftView.setObjectName("LeftView")
        self.gridLayout.addWidget(self.LeftView, 0, 2, 1, 1)
        self.DetailedView = QtWidgets.QWidget(self.CentralView)
        self.DetailedView.setMinimumSize(QtCore.QSize(800, 0))
        self.DetailedView.setObjectName("DetailedView")
        self.gridLayout.addWidget(self.DetailedView, 0, 3, 1, 1)
        self.RightView = QtWidgets.QWidget(self.CentralView)
        self.RightView.setMaximumSize(QtCore.QSize(250, 16777215))
        self.RightView.setObjectName("RightView")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.RightView)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.CategoryDetails = QtWidgets.QWidget(self.RightView)
        self.CategoryDetails.setMinimumSize(QtCore.QSize(250, 200))
        self.CategoryDetails.setMaximumSize(QtCore.QSize(250, 200))
        self.CategoryDetails.setObjectName("CategoryDetails")
        self.verticalLayout.addWidget(self.CategoryDetails)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem)
        self.widget = QtWidgets.QWidget(self.RightView)
        self.widget.setMinimumSize(QtCore.QSize(250, 300))
        self.widget.setAutoFillBackground(False)
        self.widget.setObjectName("widget")
        self.verticalLayout.addWidget(self.widget)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem1)
        self.AlgorithmDetails = QtWidgets.QWidget(self.RightView)
        self.AlgorithmDetails.setMinimumSize(QtCore.QSize(250, 300))
        self.AlgorithmDetails.setMaximumSize(QtCore.QSize(250, 300))
        self.AlgorithmDetails.setObjectName("AlgorithmDetails")
        self.verticalLayout.addWidget(self.AlgorithmDetails)
        self.gridLayout.addWidget(self.RightView, 0, 4, 1, 1)
        MainWindow.setCentralWidget(self.CentralView)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1336, 26))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        self.menuImages = QtWidgets.QMenu(self.menuBar)
        self.menuImages.setObjectName("menuImages")
        MainWindow.setMenuBar(self.menuBar)
        self.PipelineMenu = QtWidgets.QAction(MainWindow)
        self.PipelineMenu.setObjectName("PipelineMenu")
        self.actionImages = QtWidgets.QAction(MainWindow)
        self.actionImages.setObjectName("actionImages")
        self.actionLoad = QtWidgets.QAction(MainWindow)
        self.actionLoad.setObjectName("actionLoad")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionLoad_2 = QtWidgets.QAction(MainWindow)
        self.actionLoad_2.setObjectName("actionLoad_2")
        self.actionSave_2 = QtWidgets.QAction(MainWindow)
        self.actionSave_2.setObjectName("actionSave_2")
        self.actionLoad_3 = QtWidgets.QAction(MainWindow)
        self.actionLoad_3.setObjectName("actionLoad_3")
        self.actionLoad_Image_Folder = QtWidgets.QAction(MainWindow)
        self.actionLoad_Image_Folder.setObjectName("actionLoad_Image_Folder")
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionLoad_2)
        self.menuImages.addAction(self.actionSave_2)
        self.menuImages.addSeparator()
        self.menuImages.addAction(self.actionLoad_3)
        self.menuImages.addAction(self.actionLoad_Image_Folder)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuImages.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.menuFile.setTitle(_translate("MainWindow", "Pipeline"))
        self.menuImages.setTitle(_translate("MainWindow", "Image"))
        self.PipelineMenu.setText(_translate("MainWindow", "Pipeline"))
        self.PipelineMenu.setToolTip(_translate("MainWindow", "Menuentrys for saving and loading pipelines"))
        self.actionImages.setText(_translate("MainWindow", "Images"))
        self.actionImages.setToolTip(_translate("MainWindow", "Menu for saving and loading images"))
        self.actionLoad.setText(_translate("MainWindow", "Load"))
        self.actionLoad.setToolTip(_translate("MainWindow", "Load a presaved pipeline in json format"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionSave.setToolTip(_translate("MainWindow", "Save the pipeline settings in a json format. You can load your specified Pipeline in later program calls to process the same settings on other images."))
        self.actionLoad_2.setText(_translate("MainWindow", "Load"))
        self.actionLoad_2.setToolTip(_translate("MainWindow", "Load a presaved Pipeline in json format."))
        self.actionSave_2.setText(_translate("MainWindow", "Specify Output location"))
        self.actionSave_2.setToolTip(_translate("MainWindow", "Specify the default output location in yout file system. Your processed images and graphs will be stored there after processing."))
        self.actionLoad_3.setText(_translate("MainWindow", "Load Image"))
        self.actionLoad_3.setToolTip(_translate("MainWindow", "Load a single image file from the file system."))
        self.actionLoad_Image_Folder.setText(_translate("MainWindow", "Load Image Folder"))
        self.actionLoad_Image_Folder.setToolTip(_translate("MainWindow", "Load a complete folder of images. To display immediate results, the program will use the first image of the folder as default."))

