# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainView.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1355, 883)
        MainWindow.setAccessibleName("NEFI 2.0")
        self.CentralView = QtWidgets.QWidget(MainWindow)
        self.CentralView.setObjectName("CentralView")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.CentralView)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.main_window_layout = QtWidgets.QHBoxLayout()
        self.main_window_layout.setObjectName("main_window_layout")
        self.left_panel = QtWidgets.QGroupBox(self.CentralView)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.left_panel.sizePolicy().hasHeightForWidth())
        self.left_panel.setSizePolicy(sizePolicy)
        self.left_panel.setMinimumSize(QtCore.QSize(350, 0))
        self.left_panel.setMaximumSize(QtCore.QSize(350, 16777215))
        self.left_panel.setObjectName("left_panel")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.left_panel)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.clear_immediate_btn = QtWidgets.QPushButton(self.left_panel)
        self.clear_immediate_btn.setMinimumSize(QtCore.QSize(31, 31))
        self.clear_immediate_btn.setMaximumSize(QtCore.QSize(31, 31))
        self.clear_immediate_btn.setText("")
        self.clear_immediate_btn.setObjectName("clear_immediate_btn")
        self.verticalLayout_6.addWidget(self.clear_immediate_btn, 0, QtCore.Qt.AlignRight)
        self.left_scroll = QtWidgets.QScrollArea(self.left_panel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.left_scroll.sizePolicy().hasHeightForWidth())
        self.left_scroll.setSizePolicy(sizePolicy)
        self.left_scroll.setMinimumSize(QtCore.QSize(330, 0))
        self.left_scroll.setMaximumSize(QtCore.QSize(330, 16777215))
        self.left_scroll.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.left_scroll.setWidgetResizable(True)
        self.left_scroll.setObjectName("left_scroll")
        self.left_scroll_results = QtWidgets.QWidget()
        self.left_scroll_results.setGeometry(QtCore.QRect(0, 0, 330, 781))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.left_scroll_results.sizePolicy().hasHeightForWidth())
        self.left_scroll_results.setSizePolicy(sizePolicy)
        self.left_scroll_results.setMinimumSize(QtCore.QSize(330, 0))
        self.left_scroll_results.setMaximumSize(QtCore.QSize(330, 16777215))
        self.left_scroll_results.setObjectName("left_scroll_results")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.left_scroll_results)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.left_scroll_results_vbox_layout = QtWidgets.QVBoxLayout()
        self.left_scroll_results_vbox_layout.setObjectName("left_scroll_results_vbox_layout")
        self.verticalLayout_10.addLayout(self.left_scroll_results_vbox_layout)
        self.left_scroll.setWidget(self.left_scroll_results)
        self.verticalLayout_6.addWidget(self.left_scroll)
        self.main_window_layout.addWidget(self.left_panel)
        self.mid_panel = QtWidgets.QWidget(self.CentralView)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mid_panel.sizePolicy().hasHeightForWidth())
        self.mid_panel.setSizePolicy(sizePolicy)
        self.mid_panel.setMinimumSize(QtCore.QSize(300, 500))
        self.mid_panel.setObjectName("mid_panel")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.mid_panel)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.mid_panel_main_layout = QtWidgets.QVBoxLayout()
        self.mid_panel_main_layout.setContentsMargins(11, 7, 7, 0)
        self.mid_panel_main_layout.setObjectName("mid_panel_main_layout")
        self.mid_panel_layout = QtWidgets.QVBoxLayout()
        self.mid_panel_layout.setObjectName("mid_panel_layout")
        self.mid_panel_main_layout.addLayout(self.mid_panel_layout)
        self.groupBox_5 = QtWidgets.QGroupBox(self.mid_panel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_5.sizePolicy().hasHeightForWidth())
        self.groupBox_5.setSizePolicy(sizePolicy)
        self.groupBox_5.setMaximumSize(QtCore.QSize(150, 100))
        self.groupBox_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.groupBox_5.setTitle("")
        self.groupBox_5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBox_5.setFlat(True)
        self.groupBox_5.setObjectName("groupBox_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.groupBox_5)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.zoom_in = QtWidgets.QToolButton(self.groupBox_5)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../assets/images/plus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.zoom_in.setIcon(icon)
        self.zoom_in.setObjectName("zoom_in")
        self.horizontalLayout_5.addWidget(self.zoom_in)
        self.zoom_out = QtWidgets.QToolButton(self.groupBox_5)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../assets/images/minus.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.zoom_out.setIcon(icon1)
        self.zoom_out.setObjectName("zoom_out")
        self.horizontalLayout_5.addWidget(self.zoom_out)
        self.resize = QtWidgets.QToolButton(self.groupBox_5)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../assets/images/resize.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.resize.setIcon(icon2)
        self.resize.setObjectName("resize")
        self.horizontalLayout_5.addWidget(self.resize)
        self.mid_panel_main_layout.addWidget(self.groupBox_5)
        self.verticalLayout_7.addLayout(self.mid_panel_main_layout)
        self.main_window_layout.addWidget(self.mid_panel)
        self.right_panel = QtWidgets.QWidget(self.CentralView)
        self.right_panel.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.right_panel.sizePolicy().hasHeightForWidth())
        self.right_panel.setSizePolicy(sizePolicy)
        self.right_panel.setMinimumSize(QtCore.QSize(370, 500))
        self.right_panel.setMaximumSize(QtCore.QSize(370, 16777215))
        self.right_panel.setObjectName("right_panel")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.right_panel)
        self.verticalLayout_9.setContentsMargins(0, 0, -1, -1)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.input_box = QtWidgets.QGroupBox(self.right_panel)
        self.input_box.setMinimumSize(QtCore.QSize(350, 200))
        self.input_box.setMaximumSize(QtCore.QSize(350, 16777215))
        self.input_box.setObjectName("input_box")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.input_box)
        self.verticalLayout_11.setContentsMargins(-1, 11, -1, -1)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setContentsMargins(0, -1, -1, -1)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.widget_3 = QtWidgets.QWidget(self.input_box)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_3.sizePolicy().hasHeightForWidth())
        self.widget_3.setSizePolicy(sizePolicy)
        self.widget_3.setMinimumSize(QtCore.QSize(330, 40))
        self.widget_3.setMaximumSize(QtCore.QSize(340, 40))
        self.widget_3.setBaseSize(QtCore.QSize(350, 50))
        self.widget_3.setObjectName("widget_3")
        self.custom_label = QtWidgets.QLabel(self.widget_3)
        self.custom_label.setGeometry(QtCore.QRect(-10, 0, 124, 40))
        self.custom_label.setMinimumSize(QtCore.QSize(100, 30))
        self.custom_label.setMaximumSize(QtCore.QSize(130, 16777215))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.custom_label.setFont(font)
        self.custom_label.setStyleSheet("margin-left : 23px")
        self.custom_label.setObjectName("custom_label")
        self.lineEdit = QtWidgets.QLineEdit(self.widget_3)
        self.lineEdit.setGeometry(QtCore.QRect(90, 5, 150, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
        self.lineEdit.setSizePolicy(sizePolicy)
        self.lineEdit.setMinimumSize(QtCore.QSize(150, 30))
        self.lineEdit.setMaximumSize(QtCore.QSize(150, 30))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("")
        self.lineEdit.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEdit.setDragEnabled(False)
        self.lineEdit.setObjectName("lineEdit")
        self.input_btn = QtWidgets.QPushButton(self.widget_3)
        self.input_btn.setGeometry(QtCore.QRect(250, 5, 30, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.input_btn.sizePolicy().hasHeightForWidth())
        self.input_btn.setSizePolicy(sizePolicy)
        self.input_btn.setMinimumSize(QtCore.QSize(30, 30))
        self.input_btn.setMaximumSize(QtCore.QSize(30, 30))
        self.input_btn.setText("")
        self.input_btn.setObjectName("input_btn")
        self.verticalLayout_5.addWidget(self.widget_3)
        self.widget_2 = QtWidgets.QWidget(self.input_box)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy)
        self.widget_2.setMinimumSize(QtCore.QSize(330, 40))
        self.widget_2.setMaximumSize(QtCore.QSize(350, 40))
        self.widget_2.setBaseSize(QtCore.QSize(350, 50))
        self.widget_2.setStyleSheet("")
        self.widget_2.setObjectName("widget_2")
        self.label_3 = QtWidgets.QLabel(self.widget_2)
        self.label_3.setGeometry(QtCore.QRect(-10, 0, 124, 40))
        self.label_3.setMinimumSize(QtCore.QSize(100, 0))
        self.label_3.setMaximumSize(QtCore.QSize(130, 16777215))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("margin-left : 23px")
        self.label_3.setObjectName("label_3")
        self.custom_line_edit = QtWidgets.QLineEdit(self.widget_2)
        self.custom_line_edit.setGeometry(QtCore.QRect(90, 5, 150, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.custom_line_edit.sizePolicy().hasHeightForWidth())
        self.custom_line_edit.setSizePolicy(sizePolicy)
        self.custom_line_edit.setMinimumSize(QtCore.QSize(150, 30))
        self.custom_line_edit.setMaximumSize(QtCore.QSize(150, 30))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.custom_line_edit.setFont(font)
        self.custom_line_edit.setStyleSheet("")
        self.custom_line_edit.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.custom_line_edit.setObjectName("custom_line_edit")
        self.output_btn = QtWidgets.QPushButton(self.widget_2)
        self.output_btn.setGeometry(QtCore.QRect(250, 5, 30, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.output_btn.sizePolicy().hasHeightForWidth())
        self.output_btn.setSizePolicy(sizePolicy)
        self.output_btn.setMinimumSize(QtCore.QSize(30, 30))
        self.output_btn.setMaximumSize(QtCore.QSize(30, 30))
        self.output_btn.setText("")
        self.output_btn.setObjectName("output_btn")
        self.verticalLayout_5.addWidget(self.widget_2)
        self.widget = QtWidgets.QWidget(self.input_box)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setMinimumSize(QtCore.QSize(330, 40))
        self.widget.setMaximumSize(QtCore.QSize(350, 40))
        self.widget.setBaseSize(QtCore.QSize(350, 50))
        self.widget.setStyleSheet("")
        self.widget.setObjectName("widget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.horizontalLayout_3.setContentsMargins(0, 0, -1, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.widget_5 = QtWidgets.QWidget(self.widget)
        self.widget_5.setMinimumSize(QtCore.QSize(0, 40))
        self.widget_5.setObjectName("widget_5")
        self.fav_label = QtWidgets.QLabel(self.widget_5)
        self.fav_label.setGeometry(QtCore.QRect(-10, 0, 100, 40))
        self.fav_label.setMinimumSize(QtCore.QSize(100, 0))
        self.fav_label.setMaximumSize(QtCore.QSize(130, 16777215))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.fav_label.setFont(font)
        self.fav_label.setStyleSheet("margin-left : 23px")
        self.fav_label.setObjectName("fav_label")
        self.fav_pips_combo_box = QtWidgets.QComboBox(self.widget_5)
        self.fav_pips_combo_box.setGeometry(QtCore.QRect(90, 5, 150, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fav_pips_combo_box.sizePolicy().hasHeightForWidth())
        self.fav_pips_combo_box.setSizePolicy(sizePolicy)
        self.fav_pips_combo_box.setMinimumSize(QtCore.QSize(150, 30))
        self.fav_pips_combo_box.setMaximumSize(QtCore.QSize(150, 30))
        self.fav_pips_combo_box.setBaseSize(QtCore.QSize(150, 0))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setItalic(False)
        self.fav_pips_combo_box.setFont(font)
        self.fav_pips_combo_box.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.fav_pips_combo_box.setStyleSheet("")
        self.fav_pips_combo_box.setMinimumContentsLength(150)
        self.fav_pips_combo_box.setObjectName("fav_pips_combo_box")
        self.open_pip_btn = QtWidgets.QPushButton(self.widget_5)
        self.open_pip_btn.setGeometry(QtCore.QRect(250, 5, 30, 30))
        self.open_pip_btn.setMinimumSize(QtCore.QSize(30, 30))
        self.open_pip_btn.setMaximumSize(QtCore.QSize(30, 30))
        self.open_pip_btn.setText("")
        self.open_pip_btn.setObjectName("open_pip_btn")
        self.save_btn = QtWidgets.QPushButton(self.widget_5)
        self.save_btn.setGeometry(QtCore.QRect(286, 5, 30, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.save_btn.sizePolicy().hasHeightForWidth())
        self.save_btn.setSizePolicy(sizePolicy)
        self.save_btn.setMinimumSize(QtCore.QSize(30, 30))
        self.save_btn.setMaximumSize(QtCore.QSize(30, 30))
        self.save_btn.setText("")
        self.save_btn.setObjectName("save_btn")
        self.horizontalLayout_3.addWidget(self.widget_5)
        self.verticalLayout_5.addWidget(self.widget)
        self.verticalLayout_11.addLayout(self.verticalLayout_5)
        self.run_btn_widget = QtWidgets.QWidget(self.input_box)
        self.run_btn_widget.setMinimumSize(QtCore.QSize(330, 30))
        self.run_btn_widget.setMaximumSize(QtCore.QSize(145, 30))
        self.run_btn_widget.setObjectName("run_btn_widget")
        self.run_btn = QtWidgets.QPushButton(self.run_btn_widget)
        self.run_btn.setGeometry(QtCore.QRect(90, 0, 150, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(30)
        sizePolicy.setHeightForWidth(self.run_btn.sizePolicy().hasHeightForWidth())
        self.run_btn.setSizePolicy(sizePolicy)
        self.run_btn.setMinimumSize(QtCore.QSize(150, 30))
        self.run_btn.setMaximumSize(QtCore.QSize(145, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.run_btn.setFont(font)
        self.run_btn.setStyleSheet("")
        self.run_btn.setCheckable(False)
        self.run_btn.setObjectName("run_btn")
        self.verticalLayout_11.addWidget(self.run_btn_widget)
        self.verticalLayout_9.addWidget(self.input_box)
        self.pip_collapsable = QtWidgets.QGroupBox(self.right_panel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pip_collapsable.sizePolicy().hasHeightForWidth())
        self.pip_collapsable.setSizePolicy(sizePolicy)
        self.pip_collapsable.setMinimumSize(QtCore.QSize(350, 350))
        self.pip_collapsable.setMaximumSize(QtCore.QSize(350, 16777215))
        self.pip_collapsable.setBaseSize(QtCore.QSize(350, 350))
        self.pip_collapsable.setTitle("Pipeline")
        self.pip_collapsable.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.pip_collapsable.setFlat(True)
        self.pip_collapsable.setObjectName("pip_collapsable")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.pip_collapsable)
        self.verticalLayout_2.setContentsMargins(0, -1, -1, -1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget_4 = QtWidgets.QWidget(self.pip_collapsable)
        self.widget_4.setMinimumSize(QtCore.QSize(0, 31))
        self.widget_4.setObjectName("widget_4")
        self.add_btn = QtWidgets.QPushButton(self.widget_4)
        self.add_btn.setGeometry(QtCore.QRect(251, 0, 31, 31))
        self.add_btn.setMinimumSize(QtCore.QSize(31, 31))
        self.add_btn.setMaximumSize(QtCore.QSize(31, 31))
        self.add_btn.setText("")
        self.add_btn.setObjectName("add_btn")
        self.delete_btn = QtWidgets.QPushButton(self.widget_4)
        self.delete_btn.setGeometry(QtCore.QRect(287, 0, 31, 31))
        self.delete_btn.setMinimumSize(QtCore.QSize(31, 31))
        self.delete_btn.setMaximumSize(QtCore.QSize(31, 31))
        self.delete_btn.setText("")
        self.delete_btn.setObjectName("delete_btn")
        self.current_pip_label = QtWidgets.QLabel(self.widget_4)
        self.current_pip_label.setGeometry(QtCore.QRect(1, 4, 130, 22))
        self.current_pip_label.setMinimumSize(QtCore.QSize(130, 0))
        self.current_pip_label.setMaximumSize(QtCore.QSize(130, 16777215))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.current_pip_label.setFont(font)
        self.current_pip_label.setStyleSheet("margin-left : 20px")
        self.current_pip_label.setText("")
        self.current_pip_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.current_pip_label.setObjectName("current_pip_label")
        self.verticalLayout_2.addWidget(self.widget_4)
        self.line = QtWidgets.QFrame(self.pip_collapsable)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line.sizePolicy().hasHeightForWidth())
        self.line.setSizePolicy(sizePolicy)
        self.line.setMidLineWidth(1)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_2.addWidget(self.line)
        self.pip_scroll = QtWidgets.QScrollArea(self.pip_collapsable)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pip_scroll.sizePolicy().hasHeightForWidth())
        self.pip_scroll.setSizePolicy(sizePolicy)
        self.pip_scroll.setMinimumSize(QtCore.QSize(340, 200))
        self.pip_scroll.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.pip_scroll.setFrameShadow(QtWidgets.QFrame.Plain)
        self.pip_scroll.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.pip_scroll.setWidgetResizable(True)
        self.pip_scroll.setObjectName("pip_scroll")
        self.pip_scroll_vbox_layout = QtWidgets.QWidget()
        self.pip_scroll_vbox_layout.setGeometry(QtCore.QRect(0, 0, 340, 250))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pip_scroll_vbox_layout.sizePolicy().hasHeightForWidth())
        self.pip_scroll_vbox_layout.setSizePolicy(sizePolicy)
        self.pip_scroll_vbox_layout.setObjectName("pip_scroll_vbox_layout")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.pip_scroll_vbox_layout)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.pip_widget_vbox_layout = QtWidgets.QVBoxLayout()
        self.pip_widget_vbox_layout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.pip_widget_vbox_layout.setSpacing(2)
        self.pip_widget_vbox_layout.setObjectName("pip_widget_vbox_layout")
        self.verticalLayout_4.addLayout(self.pip_widget_vbox_layout)
        self.pip_scroll.setWidget(self.pip_scroll_vbox_layout)
        self.verticalLayout_2.addWidget(self.pip_scroll)
        spacerItem = QtWidgets.QSpacerItem(5, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem)
        self.verticalLayout_9.addWidget(self.pip_collapsable)
        self.settings_collapsable = QtWidgets.QGroupBox(self.right_panel)
        self.settings_collapsable.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.settings_collapsable.sizePolicy().hasHeightForWidth())
        self.settings_collapsable.setSizePolicy(sizePolicy)
        self.settings_collapsable.setMinimumSize(QtCore.QSize(350, 350))
        self.settings_collapsable.setMaximumSize(QtCore.QSize(350, 16777215))
        self.settings_collapsable.setAcceptDrops(False)
        self.settings_collapsable.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.settings_collapsable.setFlat(False)
        self.settings_collapsable.setCheckable(False)
        self.settings_collapsable.setObjectName("settings_collapsable")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.settings_collapsable)
        self.verticalLayout.setContentsMargins(0, -1, -1, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.setting_scroll = QtWidgets.QScrollArea(self.settings_collapsable)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.setting_scroll.sizePolicy().hasHeightForWidth())
        self.setting_scroll.setSizePolicy(sizePolicy)
        self.setting_scroll.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.setting_scroll.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.setting_scroll.setFrameShadow(QtWidgets.QFrame.Plain)
        self.setting_scroll.setWidgetResizable(True)
        self.setting_scroll.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.setting_scroll.setObjectName("setting_scroll")
        self.settings_scroll_vbox_layout = QtWidgets.QWidget()
        self.settings_scroll_vbox_layout.setGeometry(QtCore.QRect(0, 0, 337, 321))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.settings_scroll_vbox_layout.sizePolicy().hasHeightForWidth())
        self.settings_scroll_vbox_layout.setSizePolicy(sizePolicy)
        self.settings_scroll_vbox_layout.setBaseSize(QtCore.QSize(0, 400))
        self.settings_scroll_vbox_layout.setObjectName("settings_scroll_vbox_layout")
        self.settings_scroll_vbox_layout_2 = QtWidgets.QVBoxLayout(self.settings_scroll_vbox_layout)
        self.settings_scroll_vbox_layout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.settings_scroll_vbox_layout_2.setContentsMargins(-1, 0, -1, -1)
        self.settings_scroll_vbox_layout_2.setObjectName("settings_scroll_vbox_layout_2")
        self.select_cat_alg_vbox_layout = QtWidgets.QVBoxLayout()
        self.select_cat_alg_vbox_layout.setObjectName("select_cat_alg_vbox_layout")
        self.settings_scroll_vbox_layout_2.addLayout(self.select_cat_alg_vbox_layout)
        self.stackedWidget_Settings = QtWidgets.QStackedWidget(self.settings_scroll_vbox_layout)
        self.stackedWidget_Settings.setObjectName("stackedWidget_Settings")
        self.settings_scroll_vbox_layout_2.addWidget(self.stackedWidget_Settings)
        self.setting_scroll.setWidget(self.settings_scroll_vbox_layout)
        self.verticalLayout.addWidget(self.setting_scroll)
        self.verticalLayout_9.addWidget(self.settings_collapsable)
        self.main_window_layout.addWidget(self.right_panel)
        self.verticalLayout_3.addLayout(self.main_window_layout)
        MainWindow.setCentralWidget(self.CentralView)
        self.PipelineMenu = QtWidgets.QAction(MainWindow)
        self.PipelineMenu.setObjectName("PipelineMenu")
        self.actionImages = QtWidgets.QAction(MainWindow)
        self.actionImages.setObjectName("actionImages")
        self.actionLoad = QtWidgets.QAction(MainWindow)
        self.actionLoad.setObjectName("actionLoad")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionLoad_2 = QtWidgets.QAction(MainWindow)
        self.actionLoad_2.setObjectName("actionLoad_2")
        self.actionSave_2 = QtWidgets.QAction(MainWindow)
        self.actionSave_2.setObjectName("actionSave_2")
        self.actionLoad_3 = QtWidgets.QAction(MainWindow)
        self.actionLoad_3.setObjectName("actionLoad_3")
        self.actionLoad_Image_Folder = QtWidgets.QAction(MainWindow)
        self.actionLoad_Image_Folder.setObjectName("actionLoad_Image_Folder")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.left_panel.setTitle(_translate("MainWindow", "Immediate Results"))
        self.zoom_in.setText(_translate("MainWindow", "..."))
        self.zoom_out.setText(_translate("MainWindow", "..."))
        self.resize.setText(_translate("MainWindow", "..."))
        self.input_box.setTitle(_translate("MainWindow", "Input"))
        self.custom_label.setText(_translate("MainWindow", "Input"))
        self.label_3.setText(_translate("MainWindow", "Output"))
        self.fav_label.setText(_translate("MainWindow", "Pipeline"))
        self.run_btn.setText(_translate("MainWindow", "Run"))
        self.settings_collapsable.setTitle(_translate("MainWindow", "Settings"))
        self.PipelineMenu.setText(_translate("MainWindow", "Pipeline"))
        self.PipelineMenu.setToolTip(_translate("MainWindow", "Menuentrys for saving and loading pipelines"))
        self.actionImages.setText(_translate("MainWindow", "Images"))
        self.actionImages.setToolTip(_translate("MainWindow", "Menu for saving and loading images"))
        self.actionLoad.setText(_translate("MainWindow", "Load"))
        self.actionLoad.setToolTip(_translate("MainWindow", "Load a presaved pipeline in json format"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionSave.setToolTip(_translate("MainWindow", "Save the pipeline settings in a json format. You can load your specified Pipeline in later program calls to process the same settings on other images."))
        self.actionLoad_2.setText(_translate("MainWindow", "Load"))
        self.actionLoad_2.setToolTip(_translate("MainWindow", "Load a presaved Pipeline in json format."))
        self.actionSave_2.setText(_translate("MainWindow", "Specify Output location"))
        self.actionSave_2.setToolTip(_translate("MainWindow", "Specify the default output location in yout file system. Your processed images and graphs will be stored there after processing."))
        self.actionLoad_3.setText(_translate("MainWindow", "Load Image"))
        self.actionLoad_3.setToolTip(_translate("MainWindow", "Load a single image file from the file system."))
        self.actionLoad_Image_Folder.setText(_translate("MainWindow", "Load Image Folder"))
        self.actionLoad_Image_Folder.setToolTip(_translate("MainWindow", "Load a complete folder of images. To display immediate results, the program will use the first image of the folder as default."))

